export const endpoints = {
  _base: `${process.env.NEXT_PUBLIC_HOST_BASE}`,
  auth_changeName: `${process.env.NEXT_PUBLIC_HOST_BASE}/api/auth/change-name`,
  auth_create_oauth_session: `${process.env.NEXT_PUBLIC_HOST_BASE}/api/auth/create-oauth-session`,
  auth_loginEmail: `${process.env.NEXT_PUBLIC_HOST_BASE}/api/auth/login-email`,
  auth_logout: `${process.env.NEXT_PUBLIC_HOST_BASE}/api/auth/logout`,
  auth_me: `${process.env.NEXT_PUBLIC_HOST_BASE}/api/auth/me`,
  auth_registration: `${process.env.NEXT_PUBLIC_HOST_BASE}/api/auth/registration`,
  auth_sendVerifyEmail: `${process.env.NEXT_PUBLIC_HOST_BASE}/api/auth/send-verify-email`,
  auth_verifyEmail: `${process.env.NEXT_PUBLIC_HOST_BASE}/api/auth/verify-email`,
  posts: `${process.env.NEXT_PUBLIC_HOST_BASE}/api/posts`,
  posts_create: `${process.env.NEXT_PUBLIC_HOST_BASE}/api/posts/create-post`,
  posts_delete: `${process.env.NEXT_PUBLIC_HOST_BASE}/api/posts/delete-post`,
  posts_get_not_published: `${process.env.NEXT_PUBLIC_HOST_BASE}/api/posts/not-published-posts`,
  posts_get_post: `${process.env.NEXT_PUBLIC_HOST_BASE}/api/posts/post`,
  posts_publish: `${process.env.NEXT_PUBLIC_HOST_BASE}/api/posts/publish-post`,
  posts_update: `${process.env.NEXT_PUBLIC_HOST_BASE}/api/posts/update-post`,
  users_get_all: `${process.env.NEXT_PUBLIC_HOST_BASE}/api/users`,
  users_get_user: `${process.env.NEXT_PUBLIC_HOST_BASE}/api/users/user`,
} as const
