export const endpoints = {
  _base: `${process.env.NEXT_PUBLIC_HOST_BASE}`,
  auth_changeName: `/api/auth/change-name`,
  auth_create_avatar: `/api/auth/create-avatar`,
  auth_create_oauth_session: `/api/auth/create-oauth-session`,
  auth_delete_avatar: `/api/auth/delete-avatar`,
  auth_loginEmail: `/api/auth/login-email`,
  auth_logout: `/api/auth/logout`,
  auth_me: `/api/auth/me`,
  auth_registration: `/api/auth/registration`,
  auth_sendVerifyEmail: `/api/auth/send-verify-email`,
  auth_verifyEmail: `/api/auth/verify-email`,
  posts: `/api/posts`,
  posts_create: `/api/posts/create-post`,
  posts_delete: `/api/posts/delete-post`,
  posts_get_not_published: `/api/posts/not-published-posts`,
  posts_get_post: `/api/posts/post`,
  posts_publish: `/api/posts/publish-post`,
  posts_update: `/api/posts/update-post`,
  users_get_all: `/api/users`,
  users_get_avatar_meta: `/api/users/avatar-meta`,
  users_get_user: `/api/users/user`,
} as const
