export const routes = {
  account: '/account',
  administrator: '/administrator',
  base: '/',
  confirmEmail: '/confirm-email',
  contacts: '/contacts',
  createPost: '/create-post',
  login: '/login',
  moderator: '/moderator',
  post: '/post/',
  posts: '/posts',
  profileNotFound: '/profile-not-found',
  registration: '/registration',
  updatePost: '/edit-post/',
} as const
